### ISSUE TITLE
jsonlint-cli doesn't work on single files

### ISSUE THREAD

**Issue by CestDiego** [marionebl/jsonlint-cli#8]
I get this error:
```
> jsonlint-cli package.json
/Users/dberrocal/.nvm/versions/node/v4.4.5/lib/node_modules/jsonlint-cli/index.js:66
                        throw error;
                        ^
SyntaxError: Unexpected token /
    at Object.parse (native)
    at decoders.(anonymous function) (/Users/dberrocal/.nvm/versions/node/v4.4.5/lib/node_modules/jsonlint-cli/node_modules/cli-rc/index.js:18:15)
    at /Users/dberrocal/.nvm/versions/node/v4.4.5/lib/node_modules/jsonlint-cli/node_modules/cli-rc/index.js:126:17
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

**Comment by GabLeRoux** [comment]
You may try with a more recent version, `v4.4.5` seems old. I'd stick to nodejs lts version if I were you.
https://nodejs.org/en/

Current NodeJS version is 8.9.4 and it works fine from here.
